[package]
name = "ssd1351_spidev"
version = "0.1.0"
authors = ["Daniel Trnka <daniel.trnka@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spidev = "0.4.0"
gpio-cdev = "0.2"
memmap = "0.7.0"

